/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ObligationsRouteImport } from './routes/obligations'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ImplementationTrackerRouteImport } from './routes/implementation-tracker'
import { Route as ImplementationPlanRouteImport } from './routes/implementation-plan'
import { Route as ImpactMapRouteImport } from './routes/impact-map'
import { Route as ComplianceRegisterRouteImport } from './routes/compliance-register'
import { Route as AuditTrailRouteImport } from './routes/audit-trail'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ObligationsRoute = ObligationsRouteImport.update({
  id: '/obligations',
  path: '/obligations',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplementationTrackerRoute = ImplementationTrackerRouteImport.update({
  id: '/implementation-tracker',
  path: '/implementation-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplementationPlanRoute = ImplementationPlanRouteImport.update({
  id: '/implementation-plan',
  path: '/implementation-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactMapRoute = ImpactMapRouteImport.update({
  id: '/impact-map',
  path: '/impact-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRegisterRoute = ComplianceRegisterRouteImport.update({
  id: '/compliance-register',
  path: '/compliance-register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTrailRoute = AuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/compliance-register': typeof ComplianceRegisterRoute
  '/impact-map': typeof ImpactMapRoute
  '/implementation-plan': typeof ImplementationPlanRoute
  '/implementation-tracker': typeof ImplementationTrackerRoute
  '/inbox': typeof InboxRoute
  '/obligations': typeof ObligationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/compliance-register': typeof ComplianceRegisterRoute
  '/impact-map': typeof ImpactMapRoute
  '/implementation-plan': typeof ImplementationPlanRoute
  '/implementation-tracker': typeof ImplementationTrackerRoute
  '/inbox': typeof InboxRoute
  '/obligations': typeof ObligationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/compliance-register': typeof ComplianceRegisterRoute
  '/impact-map': typeof ImpactMapRoute
  '/implementation-plan': typeof ImplementationPlanRoute
  '/implementation-tracker': typeof ImplementationTrackerRoute
  '/inbox': typeof InboxRoute
  '/obligations': typeof ObligationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-trail'
    | '/compliance-register'
    | '/impact-map'
    | '/implementation-plan'
    | '/implementation-tracker'
    | '/inbox'
    | '/obligations'
    | '/onboarding'
    | '/settings'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-trail'
    | '/compliance-register'
    | '/impact-map'
    | '/implementation-plan'
    | '/implementation-tracker'
    | '/inbox'
    | '/obligations'
    | '/onboarding'
    | '/settings'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/audit-trail'
    | '/compliance-register'
    | '/impact-map'
    | '/implementation-plan'
    | '/implementation-tracker'
    | '/inbox'
    | '/obligations'
    | '/onboarding'
    | '/settings'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditTrailRoute: typeof AuditTrailRoute
  ComplianceRegisterRoute: typeof ComplianceRegisterRoute
  ImpactMapRoute: typeof ImpactMapRoute
  ImplementationPlanRoute: typeof ImplementationPlanRoute
  ImplementationTrackerRoute: typeof ImplementationTrackerRoute
  InboxRoute: typeof InboxRoute
  ObligationsRoute: typeof ObligationsRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obligations': {
      id: '/obligations'
      path: '/obligations'
      fullPath: '/obligations'
      preLoaderRoute: typeof ObligationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implementation-tracker': {
      id: '/implementation-tracker'
      path: '/implementation-tracker'
      fullPath: '/implementation-tracker'
      preLoaderRoute: typeof ImplementationTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implementation-plan': {
      id: '/implementation-plan'
      path: '/implementation-plan'
      fullPath: '/implementation-plan'
      preLoaderRoute: typeof ImplementationPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-map': {
      id: '/impact-map'
      path: '/impact-map'
      fullPath: '/impact-map'
      preLoaderRoute: typeof ImpactMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-register': {
      id: '/compliance-register'
      path: '/compliance-register'
      fullPath: '/compliance-register'
      preLoaderRoute: typeof ComplianceRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-trail': {
      id: '/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditTrailRoute: AuditTrailRoute,
  ComplianceRegisterRoute: ComplianceRegisterRoute,
  ImpactMapRoute: ImpactMapRoute,
  ImplementationPlanRoute: ImplementationPlanRoute,
  ImplementationTrackerRoute: ImplementationTrackerRoute,
  InboxRoute: InboxRoute,
  ObligationsRoute: ObligationsRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
